# Generated by Django 3.1.4 on 2023-03-25 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'Day',
                'verbose_name_plural': 'Days',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
            options={
                'verbose_name': 'Schedule',
                'verbose_name_plural': 'Schedules',
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_by_hour', models.FloatField(default=0, verbose_name='Price')),
                ('quantity_hours', models.IntegerField(verbose_name='Quantity hours')),
                ('total_price', models.FloatField(default=0, verbose_name='Total price')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.day', verbose_name='Day')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.schedule', verbose_name='Schedule')),
            ],
            options={
                'verbose_name': 'Rate',
                'verbose_name_plural': 'Rates',
            },
        ),
    ]
